# Generated by Django 4.1.6 on 2023-02-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_closure", "0002_homedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("category", models.CharField(max_length=4)),
                ("FSA", models.IntegerField()),
            ],
        ),
    ]
