# Generated by Django 4.1.6 on 2023-03-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_closure", "0004_alter_marketdata_latitude_alter_marketdata_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homedata", name="latitude", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="homedata", name="longitude", field=models.FloatField(),
        ),
    ]
